Repository Andrew15-5/Grocery-Store, pull requests merged in 2022-07, with the labels that each got.

#6 #5. Added function which checks that all env vars are defined
  package.json
  src/index.ts
  src/utils.ts
Labels: enhancement

#9 #4. Added functions for authentification
  package.json
  src/utils.ts
  src/utils/auth.ts
Labels: enhancement

#11 #8. Added log in logic
  public/login.html
  src/index.ts
  src/login.ts
Labels: enhancement

#14 #13. Fixed error when logged in user tries to access "/login" page
  src/login.ts
Labels: fixed bug

#16 #15. Added checkbox to "/login" page to delete cookie when browser is closed
  public/login.html
  src/login.ts
  src/utils/auth.ts
Labels: enhancement

#18 #17. Added cross redirect in "/registraion" and "/login"
  public/login.html
  public/registration.html
Labels: enhancement

#24 #22. Redid "/login" page HTML layout
  public/login.html
Labels: enhancement

#26 #19. Added log out tag to "/catalog"
  public/css/global.css
  public/js/log_out.js
  views/catalog.hbs
Labels: enhancement

#28 #27. Added auto switching tag for authorization on "/catalog" page
  public/css/global.css
  public/js/log_out.js
  src/catalog.ts
  views/catalog.hbs
Labels: enhancement

#31 #30. Added purchase button for each product on "/catalog" page
  src/catalog.ts
  src/index.ts
  views/catalog.hbs
Labels: enhancement

#35 #32. Added ability to make purchases
  public/js/show_purchase_message.js
  public/js/utils.js
  src/catalog.ts
  src/utils.ts
  views/catalog.hbs
Labels: enhancement

#36 Added ability to purchase products
  public/js/show_purchase_message.js
  public/js/utils.js
  src/catalog.ts
  src/index.ts
  src/utils.ts
  src/utils/auth.ts
  views/catalog.hbs
Labels: enhancement

#38 #37. Integrated reward_balance from ref-app
  package.json
  src/account.ts
  src/utils.ts
  views/account.hbs
Labels: enhancement, integration

#40 #39. Added generation of referral_id in "/registration"
  src/registration.ts
  src/utils.ts
Labels: enhancement, integration

#42 #41. Added referral purchase
  src/catalog.ts
Labels: enhancement, integration

#44 #43. Integrated copied-in-clipboard referral url in "/account"
  src/account.ts
  views/account.hbs
Labels: enhancement, integration

#47 Integrated ref-app; added home page
  package.json
  public/css/dark-theme.css
  public/css/global.css
  public/css/light-theme.css
  public/images/people.png
  public/images/tomato-dark.jpg
  public/images/tomato-light.png
  public/js/log_out.js
  public/js/show_purchase_message.js
  public/js/utils.js
  public/login.html
  src/account.ts
  src/catalog.ts
  src/home.ts
  src/index.ts
  src/login.ts
  src/product.ts
  src/registration.ts
  src/utils.ts
  src/utils/auth.ts
  src/utils/fetch_data.ts
  src/utils/hash.ts
  views/account.hbs
  views/catalog.hbs
  views/home.hbs
  views/product.hbs
Labels: enhancement, integration

#51 Added share button: referral link to specific product
  public/css/catalog.css
  public/js/share_referral_link.js
  src/catalog.ts
  src/product.ts
  src/utils/fetch_data.ts
  views/catalog.hbs
  views/product.hbs
Labels: enhancement, integration
